name: cat_facts
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.1
  dart_code_metrics: ^5.7.0
  intl: ^0.18.0
  flutter_bloc: ^8.1.2
  loading_animation_widget: ^1.2.0+4

  freezed_annotation: ^2.1.0
  equatable: ^2.0.5
  dio: ^5.2.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.0
  json_annotation: ^4.7.0
  cupertino_icons: ^1.0.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  hive_generator: ^2.0.0
  retrofit_generator: ^7.0.8
  freezed: ^2.3.2
  json_serializable: ^6.5.1
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


